### ISSUE TITLE
missing xproperties

### ISSUE THREAD

**Issue by RaafatTurki** [kompoth/micromess#2]
1st let me open with saying that this piece of software bridged the gap that separated me from a barless setup, nice work.

anyways, consider adding in a window and/or a class name on the popup window.
for instance I wanted to disable picom shadows but there is no way to target the popup window (xprop returns nothing).

cheers

**Comment by kompoth** [comment]
Ok, 0239579 adds name and class hints and also sets WM_NAME property.

Here is my xprop output now:
```
$ (printf "onelinestr\n"; sleep 10) | umess &
[1] 8103
$ xprop -name umess
WM_CLASS(STRING) = "umess", "umess"
WM_NAME(STRING) = "umess"
```

I not familiar with picom, but I tryed to test how it works with umess now.
Config file:
```
shadow = true;

 shadow-exclude = [
  "name = 'umess'",
  "class_g = 'umess'"
 ];
```
When I run picom with this configuration, umess window doesn't have any shadows.

**Comment by RaafatTurki** [comment]
great, cheers!
