### ISSUE TITLE
Archlinux packaging

### ISSUE THREAD

**Issue by RaafatTurki** [kompoth/micromess#5]
Having this on the aur (and possibly on main when ironed out) would be great.

I have already packaged it for my personal repo [here](https://github.com/RaafatTurki/pkgs/blob/master/pkgfiles/micromess/PKGBUILD).

I already have experience packaging on the aur so if you don't want to maintain it there I'll gladly do it.

**Comment by kompoth** [comment]
Creating AUR package would be amazing. Unfortunately right now I am unable to test PKGBUILD script and maintain package, so I will be grateful if you do that. Can I choose you as an Assignee for this task then?

What should I do to make it possible? Steps I have already done:
- made Makefile more usable in `package()` function of PKGBUILD
- created version tag v0.1 

Here is an example of PKBUILD I tried to write myself, it slightly differs from yours (can't test any of them though):
```
pkgname=micromess
pkgver=0.1
pkgrel=1
pkgdesc="A simple X pop-up"
arch=('x86_64')
license=('MIT')
url="https://github.com/kompoth/micromess"
source=("${url}/archive/v${pkgver}.tar.gz")
depends=('libx11' 'libxrandr' 'libxft')
makedepends=('???')
sha256sums=('???')

build() {
  cd "{$pkgname}-${pkgver}"
  make
}

package() {
  cd "{$pkgname}-${pkgver}"
  make PREFIX="$pkgdir/usr" install
}
```
Main points here:
- `source` now is tagged version
- more compact `package()`
- `dependencies` (I am not sure if this works, I was looking on `lemonbar` and `dwm` PKGBUILDs)

I am not sure about `makedepends` and checksum variable (do we need it?).

**Comment by RaafatTurki** [comment]
No worries, by all means assign me.
I've tested your PKGBUILD and it didn't build at 1st as there were a few issues.
I like the new `make install`.

writing a `PKGBUILD` requires following some guidelines you can read more about them [here](https://wiki.archlinux.org/title/PKGBUILD) and [here](https://wiki.archlinux.org/title/VCS_package_guidelines).

- currently `micromess` is a `-git` package, that's analogous to nightly builds, the users are always getting the latest commit.

- `PKGBUILD` allows vsc based version bumping so it automatically marks itself outdated when a new commit is pushed (also updated the PKGBUILD itself).

- `makedepends` is an array of all dependencies used to compile the package.

- checksums aren't required and can be added anytime.

I've reflected all of the above into the new [PKGBUILD](https://github.com/RaafatTurki/pkgs/blob/master/pkgfiles/micromess-git/PKGBUILD)

**Comment by kompoth** [comment]
Excellent, thanks. Especially for version bumping, that's interesting. I thought, that package maintainer has to update PKBUILD for every version or at least write some script to track versions changes. But it turned out to be much easier to do that.

Could you please load this PKGBUILD to aur?

**Comment by RaafatTurki** [comment]
[done](https://aur.archlinux.org/packages/umess-git)
